"""Domain models for the CUA system."""

from cua.models.capability import (
    ActionType,
    ApprovalState,
    Capability,
    Checkpoint,
    CheckpointType,
    ElementTarget,
    ErrorHandler,
    ErrorPolicy,
    LocatorStrategy,
    LocatorType,
    OutputSpec,
    ParameterSpec,
    RiskLevel,
    Step,
    SurfaceTarget,
)
from cua.models.execution import (
    BusinessOutcome,
    ErrorCategory,
    HardFailure,
    RecoverableCondition,
    RunResult,
    RunStatus,
    StepResult,
    StepTrace,
)
from cua.models.policy import ActionClassification, AllowlistRule, SafetyPolicy

__all__ = [
    "ActionClassification",
    "ActionType",
    "AllowlistRule",
    "ApprovalState",
    "BusinessOutcome",
    "Capability",
    "Checkpoint",
    "CheckpointType",
    "ElementTarget",
    "ErrorCategory",
    "ErrorHandler",
    "ErrorPolicy",
    "HardFailure",
    "LocatorStrategy",
    "LocatorType",
    "OutputSpec",
    "ParameterSpec",
    "RecoverableCondition",
    "RiskLevel",
    "RunResult",
    "RunStatus",
    "SafetyPolicy",
    "Step",
    "StepResult",
    "StepTrace",
    "SurfaceTarget",
]
